/**
 * Markets configuration with SEO metadata for each market address
 * This file is auto-generated by scripts/generate-seo.mjs — do not edit
 * by hand. The market list comes from the on-chain registry
 * (https://api.futarchy.seer.pm/registry/graphql, aggregator 0xc5eb43d53e2fe5fdde5faf400cc4167e5b5d4fc1);
 * legacy Supabase-era SEO content is preserved via
 * src/config/legacy-seo.json.
 *
 * Total markets: 40
 * Active markets: 5
 */

export const MARKETS_CONFIG = {
  "0x45e1064348fD8A407D6D1F59Fc64B05F633b28FC": {
    "title": "What will the impact on GNO price be if GIP-145 is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis market-145.png",
    "path": "/markets/0x45e1064348fD8A407D6D1F59Fc64B05F633b28FC",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-145 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis market-145.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-145 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/gnosis market-145.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2026-01-15T00:00:00+00:00",
      "createdAt": "2026-01-09T19:08:27.181269+00:00",
      "source": "legacy+registry",
      "resolutionOutcome": "yes"
    }
  },
  "0x4e018f1D8b93B91a0Ce186874eDb53CB6fFfCa62": {
    "title": "What will the impact on VLR price be if 'PIP-XX: Deploy liquidity into Liquity v2 VLR pool' is approved?",
    "description": "Will VeloraDAO approve and execute PIP-XX: Deploy liquidity into Liquity v2 VLR pool before 2026-02-01 00:00 UTC?",
    "image": "/assets/veloradao-market-card-2.png",
    "path": "/markets/0x4e018f1D8b93B91a0Ce186874eDb53CB6fFfCa62",
    "openGraph": {
      "title": "What will the impact on VLR price be if 'PIP-XX: Deploy liquidity into Liquity v2 VLR pool' is approved? | Futarchy",
      "description": "Will VeloraDAO approve and execute PIP-XX: Deploy liquidity into Liquity v2 VLR pool before 2026-02-01 00:00 UTC?",
      "image": "/assets/veloradao-market-card-2.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on VLR price be if 'PIP-XX: Deploy liquidity into Liquity v2 VLR pool' is approved? | Futarchy",
      "description": "Will VeloraDAO approve and execute PIP-XX: Deploy liquidity into Liquity v2 VLR pool before 2026-02-01 00:00 UTC?",
      "image": "https://futarchy.seer.pm/assets/veloradao-market-card-2.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "VLR, USDS",
      "companyId": 13,
      "approvalStatus": "on_going",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2026-02-01T00:00:00+00:00",
      "createdAt": "2026-01-07T19:17:14.166904+00:00",
      "source": "legacy"
    }
  },
  "0xFb45aE9d8e5874e85b8e23D735EB9718EfEF47Fa": {
    "title": "What is the impact on AAVE token price if AAVE token alignment proposal is approved?",
    "description": "Will $AAVE token alignment (Phase 1) proposal, or an alternative by eboado, be approved (Yes) by AaveDAO before the end of February, 2026? If eboado confirms his proposal is rejected, or if not approved by this date, resolves as (No).",
    "image": "/assets/aave-dao-market-card-1.png",
    "path": "/markets/0xFb45aE9d8e5874e85b8e23D735EB9718EfEF47Fa",
    "openGraph": {
      "title": "What is the impact on AAVE token price if AAVE token alignment proposal is approved? | Futarchy",
      "description": "Will $AAVE token alignment (Phase 1) proposal, or an alternative by eboado, be approved (Yes) by AaveDAO before the end of February, 2026? If eboado confirms his proposal is rejected, or if not approved by this date, resolves as (No).",
      "image": "/assets/aave-dao-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What is the impact on AAVE token price if AAVE token alignment proposal is approved? | Futarchy",
      "description": "Will $AAVE token alignment (Phase 1) proposal, or an alternative by eboado, be approved (Yes) by AaveDAO before the end of February, 2026? If eboado confirms his proposal is rejected, or if not approved by this date, resolves as (No).",
      "image": "https://futarchy.seer.pm/assets/aave-dao-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "0",
      "companyId": 15,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "hidden",
      "endDate": "2026-02-01T12:00:00+00:00",
      "createdAt": "2025-12-22T19:35:38.986819+00:00",
      "source": "legacy+registry",
      "resolutionOutcome": "no"
    }
  },
  "0xCac65Fd48420e736f963a40313090A693fB3Db68": {
    "title": "What will the impact on VLR price be if PIP-75 is approved?",
    "description": "Will 'PIP-75 - Fund request from a user claiming losses due to the March 2024 AugustusV6 vulnerability' be approved ('Yes') or rejected ('No') by VeloraDAO?",
    "image": "/assets/futarchy-market-pip-45.png",
    "path": "/markets/0xCac65Fd48420e736f963a40313090A693fB3Db68",
    "openGraph": {
      "title": "What will the impact on VLR price be if PIP-75 is approved? | Futarchy",
      "description": "Will 'PIP-75 - Fund request from a user claiming losses due to the March 2024 AugustusV6 vulnerability' be approved ('Yes') or rejected ('No') by VeloraDAO?",
      "image": "/assets/futarchy-market-pip-45.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on VLR price be if PIP-75 is approved? | Futarchy",
      "description": "Will 'PIP-75 - Fund request from a user claiming losses due to the March 2024 AugustusV6 vulnerability' be approved ('Yes') or rejected ('No') by VeloraDAO?",
      "image": "https://futarchy.seer.pm/assets/futarchy-market-pip-45.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "VLR, USDS",
      "companyId": 13,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-12-23T13:00:00+00:00",
      "createdAt": "2025-12-19T13:17:59.097377+00:00",
      "source": "legacy"
    }
  },
  "0x3D076d5d12341226527241f8a489D4A8863B73e5": {
    "title": "What will the impact on GNO price be if GIP-145 is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-145.png",
    "path": "/markets/0x3D076d5d12341226527241f8a489D4A8863B73e5",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-145 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-145.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-145 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-145.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-12-11T17:48:46+00:00",
      "createdAt": "2025-12-11T19:15:34.271383+00:00",
      "source": "legacy+registry",
      "resolutionOutcome": null
    }
  },
  "0xcd57aE6f64E4Ff0687daB3699611907A5f4c528B": {
    "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/kleros-proposal-1.png",
    "path": "/markets/0xcd57aE6f64E4Ff0687daB3699611907A5f4c528B",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/kleros-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/kleros-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-07-15T23:59:59+00:00",
      "createdAt": "2025-11-19T21:26:17.154733+00:00",
      "source": "legacy"
    }
  },
  "0x1b12f43F30bcF9c7B9868Ae3D1E3b574c589Fc97": {
    "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/kleros-proposal-1.png",
    "path": "/markets/0x1b12f43F30bcF9c7B9868Ae3D1E3b574c589Fc97",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/kleros-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-TEST – Futarchy-Based Governance Rule for PNK Minting is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/kleros-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-07-15T23:59:59+00:00",
      "createdAt": "2025-11-19T21:00:07.782884+00:00",
      "source": "legacy"
    }
  },
  "0xa28614aa999117C555757D56A8178F271C24d7BA": {
    "title": "What will be the price of GNO if GIP-143 is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0xa28614aa999117C555757D56A8178F271C24d7BA",
    "openGraph": {
      "title": "What will be the price of GNO if GIP-143 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will be the price of GNO if GIP-143 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-11-15T00:00:00+00:00",
      "createdAt": "2025-11-16T00:50:00.812351+00:00",
      "source": "legacy"
    }
  },
  "0x1c2431C7cea09eDEec403a550D828Df20a4Ea147": {
    "title": "Futarchy: Predict VLR impact if VeloraDAO deploys Liquity v2 liquidity",
    "description": "Will VeloraDAO approve and execute PIP-XX (Deploy liquidity into Liquity v2 VLR pool) before 2026-01-01 00:00 UTC? Outcomes: 'Yes' if governance approves AND the liquidity deployment transaction is executed on-chain. 'No' if the proposal is rejected, expires, or execution does not occur by the deadline. If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.",
    "image": "/assets/velora-market-card-1.png",
    "path": "/markets/0x1c2431C7cea09eDEec403a550D828Df20a4Ea147",
    "openGraph": {
      "title": "Futarchy: Predict VLR impact if VeloraDAO deploys Liquity v2 liquidity | Futarchy",
      "description": "Will VeloraDAO approve and execute PIP-XX (Deploy liquidity into Liquity v2 VLR pool) before 2026-01-01 00:00 UTC? Outcomes: 'Yes' if governance approves AND the liquidity deployment transaction is executed on-chain. 'No' if the proposal is rejected, expires, or execution does not occur by the deadline. If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.",
      "image": "/assets/velora-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy: Predict VLR impact if VeloraDAO deploys Liquity v2 liquidity | Futarchy",
      "description": "Will VeloraDAO approve and execute PIP-XX (Deploy liquidity into Liquity v2 VLR pool) before 2026-01-01 00:00 UTC? Outcomes: 'Yes' if governance approves AND the liquidity deployment transaction is executed on-chain. 'No' if the proposal is rejected, expires, or execution does not occur by the deadline. If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.",
      "image": "https://futarchy.seer.pm/assets/velora-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "VLR, USDS",
      "companyId": 13,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-11-15T00:00:00+00:00",
      "createdAt": "2025-11-16T00:33:38.387147+00:00",
      "source": "legacy"
    }
  },
  "0x2C1e08674f3F78f8a1426a41C41B8BF546fA481a": {
    "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price",
    "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
    "image": "/assets/kleros-market-card-81.png",
    "path": "/markets/0x2C1e08674f3F78f8a1426a41C41B8BF546fA481a",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price | Futarchy",
      "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-81.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price | Futarchy",
      "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "https://futarchy.seer.pm/assets/kleros-market-card-81.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-11-15T19:01:40+00:00",
      "createdAt": "2025-11-04T19:10:48.972077+00:00",
      "source": "legacy+registry",
      "resolutionOutcome": "no"
    }
  },
  "0x7e9Fc0C3d6C1619d4914556ad2dEe6051Ce68418": {
    "title": "What will be the price of GNO if its price is >= 130 sDAI?",
    "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0x7e9Fc0C3d6C1619d4914556ad2dEe6051Ce68418",
    "openGraph": {
      "title": "What will be the price of GNO if its price is >= 130 sDAI? | Futarchy",
      "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will be the price of GNO if its price is >= 130 sDAI? | Futarchy",
      "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-12-28T23:59:00+00:00",
      "createdAt": "2025-10-28T17:30:52.122636+00:00",
      "source": "legacy"
    }
  },
  "0x3f124FA6B58Ee61D1162175A578c588Db9689EF0": {
    "title": "What will the impact on GNO price be if GIP-140 is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0x3f124FA6B58Ee61D1162175A578c588Db9689EF0",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-140 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-140 is approved? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-10-28T11:23:00+00:00",
      "createdAt": "2025-10-21T21:40:07.62192+00:00",
      "source": "legacy"
    }
  },
  "0x7D96A3f714782710917f6045441B39483c5Dc60a": {
    "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0x7D96A3f714782710917f6045441B39483c5Dc60a",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO? | Futarchy",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-10-21T06:00:00+00:00",
      "createdAt": "2025-10-14T22:25:00.40256+00:00",
      "source": "legacy"
    }
  },
  "0x1F54f0312E85c5AFACe2bDF15AA2514BeFDB844F": {
    "title": "Futarchy: Predict SBUX impact if CEO exits before 2026",
    "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
    "image": "/assets/starbucks-market-card-1.png",
    "path": "/markets/0x1F54f0312E85c5AFACe2bDF15AA2514BeFDB844F",
    "openGraph": {
      "title": "Futarchy: Predict SBUX impact if CEO exits before 2026 | Futarchy",
      "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
      "image": "/assets/starbucks-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy: Predict SBUX impact if CEO exits before 2026 | Futarchy",
      "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
      "image": "https://futarchy.seer.pm/assets/starbucks-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "0",
      "companyId": 12,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": null,
      "createdAt": "2025-10-13T20:01:56.614539+00:00",
      "source": "legacy"
    }
  },
  "0x2A4b52B47625431Fdc6fE58CeD3086E76c1f6bbf": {
    "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes",
    "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
    "image": "/assets/tesla-market-card-1.png",
    "path": "/markets/0x2A4b52B47625431Fdc6fE58CeD3086E76c1f6bbf",
    "openGraph": {
      "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes | Futarchy",
      "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
      "image": "/assets/tesla-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes | Futarchy",
      "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
      "image": "https://futarchy.seer.pm/assets/tesla-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "TSLAON, USDS",
      "companyId": 11,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-11-15T00:00:00+00:00",
      "createdAt": "2025-09-23T22:08:49.873764+00:00",
      "source": "legacy"
    }
  },
  "0xa80641Bf70483A3524713A396deE0ebD642CEaEA": {
    "title": "Futarchy Governance Prediction: GIP-133 Approval Impact",
    "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
    "image": "/assets/gnosis-market-card-133.png",
    "path": "/markets/0xa80641Bf70483A3524713A396deE0ebD642CEaEA",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy",
      "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
      "image": "/assets/gnosis-market-card-133.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy",
      "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-133.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-08-21T17:47:45+00:00",
      "createdAt": "2025-08-21T18:15:37.091354+00:00",
      "source": "legacy"
    }
  },
  "0x0842961509da168bab5f02e81ad81230c930d48a": {
    "title": "Futarchy Governance Prediction: GIP-133 Approval Impact",
    "description": "Test",
    "image": "/assets/gnosis-market-card-133.png",
    "path": "/markets/0x0842961509da168bab5f02e81ad81230c930d48a",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy",
      "description": "Test",
      "image": "/assets/gnosis-market-card-133.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy",
      "description": "Test",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-133.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-08-18T20:58:10.373428+00:00",
      "source": "legacy"
    }
  },
  "0x7dbEC3FfB25c8c0fEcB3fCd4613EffC7f72008aC": {
    "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price",
    "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
    "image": "/assets/kleros-market-card-78.png",
    "path": "/markets/0x7dbEC3FfB25c8c0fEcB3fCd4613EffC7f72008aC",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price | Futarchy",
      "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-78.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price | Futarchy",
      "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "https://futarchy.seer.pm/assets/kleros-market-card-78.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-08-15T17:20:52+00:00",
      "createdAt": "2025-08-15T18:33:09.781363+00:00",
      "source": "legacy"
    }
  },
  "0xA94aB35282118f38b0b4FF89dDA7A5c04aD49371": {
    "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact",
    "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
    "image": "/assets/kleros-market-card-1-bg.png",
    "path": "/markets/0xA94aB35282118f38b0b4FF89dDA7A5c04aD49371",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact | Futarchy",
      "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
      "image": "/assets/kleros-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact | Futarchy",
      "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
      "image": "https://futarchy.seer.pm/assets/kleros-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-16T19:57:54+00:00",
      "createdAt": "2025-07-29T20:38:30.621088+00:00",
      "source": "legacy"
    }
  },
  "0xBFE2b1B3746e401081C2abb56913c2d7042FA94d": {
    "title": "Futarchy Governance Market: GIP-128 Approval Prediction",
    "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
    "image": "/assets/gnosis-market-card-1-bg.png",
    "path": "/markets/0xBFE2b1B3746e401081C2abb56913c2d7042FA94d",
    "openGraph": {
      "title": "Futarchy Governance Market: GIP-128 Approval Prediction | Futarchy",
      "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
      "image": "/assets/gnosis-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: GIP-128 Approval Prediction | Futarchy",
      "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-07-16T19:56:14+00:00",
      "createdAt": "2025-07-16T20:32:35.447294+00:00",
      "source": "legacy"
    }
  },
  "0x5acae07AA3Cffe25b3fBef3732f8E313BBbD5115": {
    "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote",
    "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
    "image": "/assets/gnosis-market-card-1-bg.png",
    "path": "/markets/0x5acae07AA3Cffe25b3fBef3732f8E313BBbD5115",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote | Futarchy",
      "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
      "image": "/assets/gnosis-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote | Futarchy",
      "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-07-16T19:56:14+00:00",
      "createdAt": "2025-07-16T19:50:48.368972+00:00",
      "source": "legacy"
    }
  },
  "0xC5A3Ff432233cceab9b40a568966FcaD54a24BeB": {
    "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote",
    "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0xC5A3Ff432233cceab9b40a568966FcaD54a24BeB",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote | Futarchy",
      "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote | Futarchy",
      "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "test",
      "endDate": "2025-07-16T02:12:28+00:00",
      "createdAt": "2025-07-16T04:34:32.191909+00:00",
      "source": "legacy"
    }
  },
  "0xec50a351C0A4A122DC614058C0481Bb9487Abdaa": {
    "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval?",
    "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
    "image": "/assets/kleros-market-card-2-bg.png",
    "path": "/markets/0xec50a351C0A4A122DC614058C0481Bb9487Abdaa",
    "openGraph": {
      "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval? | Futarchy",
      "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
      "image": "/assets/kleros-market-card-2-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval? | Futarchy",
      "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
      "image": "https://futarchy.seer.pm/assets/kleros-market-card-2-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-15T23:59:59+00:00",
      "createdAt": "2025-06-30T01:21:31.393888+00:00",
      "source": "legacy"
    }
  },
  "0xf36e2f05E8F45954d896b2ed72cD2a0bAB6A6Dd7": {
    "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact",
    "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
    "image": "/kip76",
    "path": "/markets/0xf36e2f05E8F45954d896b2ed72cD2a0bAB6A6Dd7",
    "openGraph": {
      "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact | Futarchy",
      "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
      "image": "/kip76",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact | Futarchy",
      "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
      "image": "https://futarchy.seer.pm/kip76"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "test",
      "endDate": "2025-07-16T23:59:59+00:00",
      "createdAt": "2025-06-30T01:10:58.33154+00:00",
      "source": "legacy"
    }
  },
  "0xa6A71F5335447B1e711ab9c78c52a24BE6c9f997": {
    "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact",
    "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
    "image": "/assets/kleros-proposal-1.png",
    "path": "/markets/0xa6A71F5335447B1e711ab9c78c52a24BE6c9f997",
    "openGraph": {
      "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact | Futarchy",
      "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
      "image": "/assets/kleros-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact | Futarchy",
      "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
      "image": "https://futarchy.seer.pm/assets/kleros-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T23:59:59+00:00",
      "createdAt": "2025-06-29T04:28:09.981958+00:00",
      "source": "legacy"
    }
  },
  "0x3e2176000a869FDDD5A4D58A66513fa834955570": {
    "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact",
    "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0x3e2176000a869FDDD5A4D58A66513fa834955570",
    "openGraph": {
      "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact | Futarchy",
      "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact | Futarchy",
      "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "defi",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-06-23T19:58:37.668206+00:00",
      "source": "legacy"
    }
  },
  "0x757fAF022abf920E110d6C4DbC2477A99788F447": {
    "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market",
    "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
    "image": "/assets/gnosis-market-card-6-bg.png",
    "path": "/markets/0x757fAF022abf920E110d6C4DbC2477A99788F447",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market | Futarchy",
      "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
      "image": "/assets/gnosis-market-card-6-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market | Futarchy",
      "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-6-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-06-20T19:27:26.183123+00:00",
      "source": "legacy"
    }
  },
  "0x9590dAF4d5cd4009c3F9767C5E7668175cFd37CF": {
    "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain",
    "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
    "image": "/assets/gnosis-market-card-7-bg.png",
    "path": "/markets/0x9590dAF4d5cd4009c3F9767C5E7668175cFd37CF",
    "openGraph": {
      "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain | Futarchy",
      "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
      "image": "/assets/gnosis-market-card-7-bg.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain | Futarchy",
      "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
      "image": "https://futarchy.seer.pm/assets/gnosis-market-card-7-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-12-31T23:59:59+00:00",
      "createdAt": "2025-06-16T22:24:01.956427+00:00",
      "source": "legacy"
    }
  },
  "0xDA36a35CA4Fe6214C37a452159C0C9EAd45D5919": {
    "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact",
    "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
    "image": "/assets/gnosis-proposal-1.webp",
    "path": "/markets/0xDA36a35CA4Fe6214C37a452159C0C9EAd45D5919",
    "openGraph": {
      "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact | Futarchy",
      "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
      "image": "/assets/gnosis-proposal-1.webp",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact | Futarchy",
      "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
      "image": "https://futarchy.seer.pm/assets/gnosis-proposal-1.webp"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-01T02:59:00+00:00",
      "createdAt": "2025-05-26T22:17:47.210777+00:00",
      "source": "legacy"
    }
  },
  "0x026b7e9473bcd860fa5c3e11a98f9312fe4b1859": {
    "title": "TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ('Yes') or rejected ('No') by GnosisDAO? If unresolved by 2025-09-30 23:59 UTC, it resolves to 'No'.",
    "description": "Live futarchy prediction market by Gnosis: TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ...",
    "image": "/assets/og-default.png",
    "path": "/markets/0x026b7e9473bcd860fa5c3e11a98f9312fe4b1859",
    "openGraph": {
      "title": "TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ('Yes') or rejected ('No') by GnosisDAO? If unresolved by 2025-09-30 23:59 UTC, it resolves to 'No'. | Futarchy",
      "description": "Live futarchy prediction market by Gnosis: TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ...",
      "image": "https://futarchy.seer.pm/assets/og-default.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ('Yes') or rejected ('No') by GnosisDAO? If unresolved by 2025-09-30 23:59 UTC, it resolves to 'No'. | Futarchy",
      "description": "Live futarchy prediction market by Gnosis: TEST4-Will 'GIP-133: Should Gnosis DAO extend the Gnosis Pay Cashback budget (GIP-110) by 2,000 GNO?' be approved ...",
      "image": "https://futarchy.seer.pm/assets/og-default.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "source": "registry",
      "organization": "Gnosis",
      "organizationId": "0x818fdf727aa4672c80bbfd47ee13975080ac40e5",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": null
    }
  },
  "0x0cae5e6f520e52e3d6a93c856bb6dbf7781f2e31": {
    "title": "What will the impact on PNK price be if KIP-88 is approved?",
    "description": "Will KIP-88 (DAO Guidance to the Cooperative) be approved ('Yes') or rejected ('No') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, results as ('No').",
    "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
    "path": "/markets/0x0cae5e6f520e52e3d6a93c856bb6dbf7781f2e31",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-88 is approved? | Futarchy",
      "description": "Will KIP-88 (DAO Guidance to the Cooperative) be approved ('Yes') or rejected ('No') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, results as ('No').",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-88 is approved? | Futarchy",
      "description": "Will KIP-88 (DAO Guidance to the Cooperative) be approved ('Yes') or rejected ('No') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, results as ('No').",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "Kleros DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "Kleros DAO",
      "organizationId": "0xaab097ead5c2db1ca7b1e5034224a2118edabe36",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": 1780660800
    }
  },
  "0x0d78b95fca9f3e1b588271a330b0d6f731ec38aa": {
    "title": "What will the impact on ETH price be if EIP-8363 is Scheduled for Inclusion in Hegotá?",
    "description": "Resolves YES if, at any time before 2026-10-24 00:00 UTC, EIP-8363 is listed under the 'Scheduled for Inclusion' section of EIP-8081 (Hardfork Meta - Hegotá) as merged in the master branch of the ethereum/EIPs GitHub repository. If EIP-8081 is renumbered or replaced, the successor Hardfork Meta EIP for the same network upgrade counts. Listing under any other section does not count. Later removal after listing does not change a YES. Only EIP number 8363 counts. Otherwise resolves NO.",
    "image": "/assets/eth-eip8363-market-card.png",
    "path": "/markets/0x0d78b95fca9f3e1b588271a330b0d6f731ec38aa",
    "openGraph": {
      "title": "What will the impact on ETH price be if EIP-8363 is Scheduled for Inclusion in Hegotá? | Futarchy",
      "description": "Resolves YES if, at any time before 2026-10-24 00:00 UTC, EIP-8363 is listed under the 'Scheduled for Inclusion' section of EIP-8081 (Hardfork Meta - Hegotá) as merged in the master branch of the ethereum/EIPs GitHub repository. If EIP-8081 is renumbered or replaced, the successor Hardfork Meta EIP for the same network upgrade counts. Listing under any other section does not count. Later removal after listing does not change a YES. Only EIP number 8363 counts. Otherwise resolves NO.",
      "image": "https://futarchy.seer.pm/assets/eth-eip8363-market-card.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on ETH price be if EIP-8363 is Scheduled for Inclusion in Hegotá? | Futarchy",
      "description": "Resolves YES if, at any time before 2026-10-24 00:00 UTC, EIP-8363 is listed under the 'Scheduled for Inclusion' section of EIP-8081 (Hardfork Meta - Hegotá) as merged in the master branch of the ethereum/EIPs GitHub repository. If EIP-8081 is renumbered or replaced, the successor Hardfork Meta EIP for the same network upgrade counts. Listing under any other section does not count. Later removal after listing does not change a YES. Only EIP number 8363 counts. Otherwise resolves NO.",
      "image": "https://futarchy.seer.pm/assets/eth-eip8363-market-card.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "Ethereum"
    ],
    "category": "trading",
    "isActive": true,
    "metadata": {
      "source": "registry",
      "organization": "Ethereum",
      "organizationId": "0xe27f436c4ca24944bda49d18020aec44cc769396",
      "chainId": 1,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": 1792800000
    }
  },
  "0x4120de9931fd29c8a6effea4df57a7c8760c1677": {
    "title": "What will the impact on GNO price be if GIP-153 is passed?",
    "description": "GIP-153: Should Gnosis Chain transition into the Ethereum Economic Zone?",
    "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
    "path": "/markets/0x4120de9931fd29c8a6effea4df57a7c8760c1677",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-153 is passed? | Futarchy",
      "description": "GIP-153: Should Gnosis Chain transition into the Ethereum Economic Zone?",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-153 is passed? | Futarchy",
      "description": "GIP-153: Should Gnosis Chain transition into the Ethereum Economic Zone?",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "Gnosis DAO"
    ],
    "category": "trading",
    "isActive": true,
    "metadata": {
      "source": "registry",
      "organization": "Gnosis DAO",
      "organizationId": "0x3fd2e8e71f75eed4b5c507706c413e33e0661bbf",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": null
    }
  },
  "0x47c80f5f701ebc5f25cab64e660f0577890729c2": {
    "title": "What will the impact on GNO price be if GIP-149 is approved?",
    "description": "Will GIP-149 (Should Gnosis DAO fund continued support of Revoke.cash?) be approved (\"Yes\") or rejected (\"No\") by GnosisDAO? If the proposal is not approved by Mar 5, 2026 - 12:30 PM (UTC), results as (\"No\").",
    "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
    "path": "/markets/0x47c80f5f701ebc5f25cab64e660f0577890729c2",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-149 is approved? | Futarchy",
      "description": "Will GIP-149 (Should Gnosis DAO fund continued support of Revoke.cash?) be approved (\"Yes\") or rejected (\"No\") by GnosisDAO? If the proposal is not approved by Mar 5, 2026 - 12:30 PM (UTC), results as (\"No\").",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-149 is approved? | Futarchy",
      "description": "Will GIP-149 (Should Gnosis DAO fund continued support of Revoke.cash?) be approved (\"Yes\") or rejected (\"No\") by GnosisDAO? If the proposal is not approved by Mar 5, 2026 - 12:30 PM (UTC), results as (\"No\").",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "Gnosis DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "Gnosis DAO",
      "organizationId": "0x3fd2e8e71f75eed4b5c507706c413e33e0661bbf",
      "chainId": 100,
      "resolutionStatus": "resolved",
      "resolutionOutcome": "no",
      "visibility": "public",
      "closeTimestamp": 1772713800
    }
  },
  "0x84412fe9d088c1d8dd676a7be9a3d5d0291ab1cf": {
    "title": "What will the impact on PNK price be if KIP-90 is approved?",
    "description": "Will KIP-90 (Cooperative Spending Disclosure) be approved ('For') or rejected ('Against') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, resolves as ('Against'). Snapshot: https://snapshot.org/#/s:kleros.eth/proposal/0xba2749a4f1283da9d1ca925d9f17bf712fa06a23e6a07d759c54340277820932",
    "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
    "path": "/markets/0x84412fe9d088c1d8dd676a7be9a3d5d0291ab1cf",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-90 is approved? | Futarchy",
      "description": "Will KIP-90 (Cooperative Spending Disclosure) be approved ('For') or rejected ('Against') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, resolves as ('Against'). Snapshot: https://snapshot.org/#/s:kleros.eth/proposal/0xba2749a4f1283da9d1ca925d9f17bf712fa06a23e6a07d759c54340277820932",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-90 is approved? | Futarchy",
      "description": "Will KIP-90 (Cooperative Spending Disclosure) be approved ('For') or rejected ('Against') by Kleros Governance? If the proposal is not approved by the end of the Snapshot vote, resolves as ('Against'). Snapshot: https://snapshot.org/#/s:kleros.eth/proposal/0xba2749a4f1283da9d1ca925d9f17bf712fa06a23e6a07d759c54340277820932",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "Kleros DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "Kleros DAO",
      "organizationId": "0xaab097ead5c2db1ca7b1e5034224a2118edabe36",
      "chainId": 100,
      "resolutionStatus": "unresolved",
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": 1783086060
    }
  },
  "0x8922b043efc0d2ff9001bf37909dd7376d15cdf7": {
    "title": "What impact will be on GNO if GIP-XX pass?",
    "description": "GIP-XX is lorem ipsum",
    "image": "/assets/og-default.png",
    "path": "/markets/0x8922b043efc0d2ff9001bf37909dd7376d15cdf7",
    "openGraph": {
      "title": "What impact will be on GNO if GIP-XX pass? | Futarchy",
      "description": "GIP-XX is lorem ipsum",
      "image": "https://futarchy.seer.pm/assets/og-default.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What impact will be on GNO if GIP-XX pass? | Futarchy",
      "description": "GIP-XX is lorem ipsum",
      "image": "https://futarchy.seer.pm/assets/og-default.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "source": "registry",
      "organization": "Gnosis",
      "organizationId": "0x818fdf727aa4672c80bbfd47ee13975080ac40e5",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": null
    }
  },
  "0xa3bfb330364ec836442290dfb5604343e0ec4efc": {
    "title": "What will be the impact on COW price if CIP-83 is approved",
    "description": "Replenish Team Grant with 5% base + up to 10% performance-linked incentives.",
    "image": "https://swap.cow.fi/images/og-meta-cowswap.png?v=4",
    "path": "/markets/0xa3bfb330364ec836442290dfb5604343e0ec4efc",
    "openGraph": {
      "title": "What will be the impact on COW price if CIP-83 is approved | Futarchy",
      "description": "Replenish Team Grant with 5% base + up to 10% performance-linked incentives.",
      "image": "https://swap.cow.fi/images/og-meta-cowswap.png?v=4",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will be the impact on COW price if CIP-83 is approved | Futarchy",
      "description": "Replenish Team Grant with 5% base + up to 10% performance-linked incentives.",
      "image": "https://swap.cow.fi/images/og-meta-cowswap.png?v=4"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "COW",
      "CoW DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "CoW DAO",
      "organizationId": "0xe071734b1ce5332da778fb1ffd79456375d420d9",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": 1770000000
    }
  },
  "0xb607bd7c7201e966e6a150cd6ef1d08db55cad5d": {
    "title": "What will the impact on PNK price be if KIP-86 is approved?",
    "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
    "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
    "path": "/markets/0xb607bd7c7201e966e6a150cd6ef1d08db55cad5d",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-86 is approved? | Futarchy",
      "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-86 is approved? | Futarchy",
      "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
      "image": "https://coin-images.coingecko.com/coins/images/3833/large/kleros.png?1696504500"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "Kleros DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "Kleros DAO",
      "organizationId": "0xaab097ead5c2db1ca7b1e5034224a2118edabe36",
      "chainId": 100,
      "resolutionStatus": "resolved",
      "resolutionOutcome": "yes",
      "visibility": "public",
      "closeTimestamp": 1775001599
    }
  },
  "0xe7f5f349a44ffb7222dff6c308233f226c901df5": {
    "title": "What will the impact on PNK price be if KIP-86 is approved?",
    "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
    "image": "/assets/og-default.png",
    "path": "/markets/0xe7f5f349a44ffb7222dff6c308233f226c901df5",
    "openGraph": {
      "title": "What will the impact on PNK price be if KIP-86 is approved? | Futarchy",
      "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
      "image": "https://futarchy.seer.pm/assets/og-default.png",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on PNK price be if KIP-86 is approved? | Futarchy",
      "description": "Will KIP-86 (Exclude PNK held by the Kleros Cooperative from KIP-66) be approved ('Yes') or rejected ('No') by Kleros Governance? If proposal is not approved by the end of March 2026, results as ('No').",
      "image": "https://futarchy.seer.pm/assets/og-default.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "Kleros Dao"
    ],
    "category": "trading",
    "isActive": true,
    "metadata": {
      "source": "registry",
      "organization": "Kleros Dao",
      "organizationId": "0xcb9b0aef0687aaf7082eda3b2715001b4ea213fd",
      "chainId": 100,
      "resolutionStatus": null,
      "resolutionOutcome": null,
      "visibility": "public",
      "closeTimestamp": null
    }
  },
  "0xece80208cb8376be311ce0f5ea4ef73850a0dcf0": {
    "title": "What will the impact on GNO price be if GIP-151 is passed?",
    "description": "Will GIP-151 (one-time pro-rata treasury redemption) be passed by GnosisDAO? Resolves Yes if GIP-151 is passed by GnosisDAO; otherwise resolves No.",
    "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
    "path": "/markets/0xece80208cb8376be311ce0f5ea4ef73850a0dcf0",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-151 is passed? | Futarchy",
      "description": "Will GIP-151 (one-time pro-rata treasury redemption) be passed by GnosisDAO? Resolves Yes if GIP-151 is passed by GnosisDAO; otherwise resolves No.",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg",
      "type": "website",
      "siteName": "Futarchy"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-151 is passed? | Futarchy",
      "description": "Will GIP-151 (one-time pro-rata treasury redemption) be passed by GnosisDAO? Resolves Yes if GIP-151 is passed by GnosisDAO; otherwise resolves No.",
      "image": "https://www.cryptoninjas.net/wp-content/uploads/gnosis-crypto-ninjas.jpg"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "Gnosis DAO"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "source": "registry",
      "organization": "Gnosis DAO",
      "organizationId": "0x3fd2e8e71f75eed4b5c507706c413e33e0661bbf",
      "chainId": 100,
      "resolutionStatus": "resolved",
      "resolutionOutcome": "yes",
      "visibility": "public",
      "closeTimestamp": 1782486884
    }
  }
};

/**
 * Get all market addresses that should be statically generated
 */
export function getStaticMarketAddresses() {
  return Object.keys(MARKETS_CONFIG);
}

/**
 * Get market configuration by address
 */
export function getMarketConfig(address) {
  return MARKETS_CONFIG[address] || null;
}

/**
 * Get all active market configurations
 */
export function getAllActiveMarkets() {
  return Object.entries(MARKETS_CONFIG)
    .filter(([_, config]) => config.isActive)
    .map(([address, config]) => ({ address, ...config }));
}

/**
 * Generate dynamic SEO metadata for a market
 */
export function generateMarketSEO(address, marketData = null) {
  const config = getMarketConfig(address);
  if (!config) return null;

  // Allow dynamic override from marketData if available
  const title = marketData?.seoTitle || config.title;
  const description = marketData?.seoDescription || config.description;
  const image = marketData?.seoImage || config.image;

  return {
    title: `${title} | Futarchy`,
    description,
    image,
    url: `https://futarchy.seer.pm${config.path}`,
    openGraph: {
      ...config.openGraph,
      title: marketData?.seoTitle ? `${marketData.seoTitle} | Futarchy` : config.openGraph.title,
      description: marketData?.seoDescription || config.openGraph.description,
      image: marketData?.seoImage || config.openGraph.image,
      url: `https://futarchy.seer.pm${config.path}`
    },
    twitter: {
      ...config.twitter,
      title: marketData?.seoTitle ? `${marketData.seoTitle} | Futarchy` : config.twitter.title,
      description: marketData?.seoDescription || config.twitter.description,
      image: marketData?.seoImage || config.twitter.image
    }
  };
}
