#!/usr/bin/env node

/**
 * Writes out/sitemap.xml after `next build` (wired as the `postbuild`
 * npm script). Lists the static routes below plus every /markets/<address>
 * page the export produced, taken from src/config/marketAddresses.js
 * (generated by scripts/generate-seo.mjs).
 */

import fs from 'fs';
import path from 'path';

const SITE_ORIGIN = 'https://futarchy.seer.pm';
const OUT_DIR = path.join(process.cwd(), 'out');
const ADDRESSES_PATH = path.join(process.cwd(), 'src', 'config', 'marketAddresses.js');

const STATIC_ROUTES = ['/', '/companies'];

function readMarketAddresses() {
  // marketAddresses.js is ESM-for-Next inside a CJS package, so read the
  // array literal instead of importing it.
  const source = fs.readFileSync(ADDRESSES_PATH, 'utf8');
  const match = source.match(/STATIC_MARKET_ADDRESSES\s*=\s*(\[[\s\S]*?\]);/);
  if (!match) throw new Error(`No STATIC_MARKET_ADDRESSES array in ${ADDRESSES_PATH}`);
  return JSON.parse(match[1]);
}

function main() {
  if (!fs.existsSync(OUT_DIR)) {
    console.error(`❌ ${OUT_DIR} does not exist — run next build first`);
    process.exit(1);
  }

  const marketRoutes = readMarketAddresses()
    .map((address) => `/markets/${address}`)
    // Only list pages the export actually wrote.
    .filter((route) => fs.existsSync(path.join(OUT_DIR, `${route}.html`)));

  const urls = [...STATIC_ROUTES, ...marketRoutes]
    .map((route) => `  <url><loc>${SITE_ORIGIN}${route === '/' ? '/' : route}</loc></url>`)
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  fs.writeFileSync(path.join(OUT_DIR, 'sitemap.xml'), xml, 'utf8');
  console.log(`🗺️  Wrote out/sitemap.xml (${STATIC_ROUTES.length + marketRoutes.length} URLs)`);
}

main();
